### ISSUE TITLE
Missing git tags.

### ISSUE THREAD

**Issue by justinmcp** [swift-server/swift-aws-lambda-events#3]
### Expected behavior
Package is correctly installed.

### Actual behavior
```
error: Dependencies could not be resolved because no versions of 'swift-aws-lambda-events' match the requirement 0.1.0..<1.0.0 and root depends on 'swift-aws-lambda-events' 0.1.0..<1.0.0.
```

There are no appropriate git tags on the repository.

### Steps to reproduce
1. Add as dependency to Package.swift
2. Attempt install/build/etc.

### Swift & OS version (output of `swift --version && uname -a`)
Apple Swift version 5.4.2 (swiftlang-1205.0.28.2 clang-1205.0.19.57).
Darwin breathwork.local 20.4.0 Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:47 PDT 2021; root:xnu-7195.101.2~1/RELEASE_X86_64 x86_64

**Comment by saltzmanjoelh** [comment]
@justinmcp You can use this in the meantime

 `.package(url: "https://github.com/swift-server/swift-aws-lambda-events", .branch("main")),`

**Comment by adam-fowler** [comment]
0.1.0 has just been tagged so I assume this can be closed.

**Comment by sebsto** [comment]
I think this issue can be closed @fabianfett

**Comment by sebsto** [comment]
I think this issue can be closed @tomerd @tachyonics
