### ISSUE TITLE
Should Package@swift-5.4.swift and 5.5 be removed?

### ISSUE THREAD

**Issue by adam-fowler** [swift-server/swift-aws-lambda-events#31]
It appears Swift 5.7 is required now. If so the 5.4 and 5.5 Package.swift should probably be removed.

Similarly the [docker-compose.al2.56.yaml](https://github.com/swift-server/swift-aws-lambda-events/blob/main/docker/docker-compose.al2.56.yaml) file could be removed

**Comment by sebsto** [comment]
Just create https://github.com/swift-server/swift-aws-lambda-events/pull/49
I let you review and approve if you have no feedback
