### ISSUE TITLE
Use https://github.com/apple/swift-http-types ?

### ISSUE THREAD

**Issue by jsonfry** [swift-server/swift-aws-lambda-events#46]
This is more of a question or thought than a bug...

There's some HTTP implementation here:

 https://github.com/swift-server/swift-aws-lambda-events/blob/main/Sources/AWSLambdaEvents/Utils/HTTP.swift

that has a lot of overlap with the recent https://github.com/apple/swift-http-types library.

Would it be a good idea to use the swift-http-types library instead?

**Comment by tomerd** [comment]
could be interesting for sure. do you want to submit a PR?

**Comment by jsonfry** [comment]
I may well have a go at it in the next couple of weeks

**Comment by sebsto** [comment]
resolved by https://github.com/swift-server/swift-aws-lambda-events/pull/47
