### ISSUE TITLE
Make requestContext in APIGatewayLambdaAuthorizerRequest public

### ISSUE THREAD

**Issue by khinkson** [swift-server/swift-aws-lambda-events#58]
### Expected behavior
I would like to access the requestContext stored property in the APIGatewayLambdaAuthorizerRequest struct.

### Actual behavior
The requestContext stored property is not marked as public and cannot be accessed. There is information in the context that can be relevant in deciding if to authorize requests.

**Comment by sebsto** [comment]
Thank you @khinkson for having reported this.
This is fixed by https://github.com/swift-server/swift-aws-lambda-events/commit/2d9612d6bff935a89a1152830068ae6d1f7676a6
